export default [
  {
    method: 'POST',
    path: '/json',
    headers: {
      'content-type': 'application/json'
    },
    // small json body
    body: JSON.stringify({
      small: 'json body'
    })
  },

  {
    method: 'POST',
    path: '/json',
    headers: {
      'content-type': 'application/json'
    },
    // medium json body
    // (yes I stole this from the first google result for "example json payload")
    body: JSON.stringify({
      rowset: {
        coldesc: [{
          type: 'string',
          name: 'Identifier'
        }, {
          type: 'string',
          name: 'Node'
        }, {
          type: 'string',
          name: 'Manager'
        }, {
          type: 'string',
          name: 'Agent'
        }, {
          type: 'string',
          name: 'AlertKey'
        }, {
          type: 'integer',
          name: 'Severity'
        }, {
          type: 'integer',
          name: 'Type'
        }, {
          type: 'string',
          name: 'Summary'
        }, {
          type: 'integer',
          name: 'Acknowledged'
        }, {
          type: 'string',
          name: 'Location'
        }, {
          type: 'utc',
          name: 'FirstOccurrence'
        }, {
          type: 'utc',
          name: 'LastOccurrence'
        }, {
          type: 'integer',
          name: 'OwnerUID'
        }, {
          type: 'integer',
          name: 'OwnerGID'
        }],
        rows: [{
          FirstOccurrence: 1341412087,
          Node: 'localhost',
          AlertKey: 'JUnitEventInstance',
          Agent: 'createEventNew()',
          Summary: 'This is a test event generated by the JUnit REST Event Tests.(0)',
          LastOccurrence: 1341412087,
          Acknowledged: 0,
          Identifier: 'JUnitEventTestInstance####0',
          Manager: 'com.ibm.netcool.omnibus.ws.junit.rest.schema.utils.TableRowEvent',
          OwnerGID: 0,
          Location: 'NOT UPDATED',
          Type: 1,
          Severity: 4,
          OwnerUID: 0
        }],
        affectedRows: 0
      }
    })
  },

  {
    method: 'POST',
    path: '/json',
    headers: {
      'content-type': 'application/json'
    },
    // large json body
    body: JSON.stringify((() => {
      const body = {};
      for (let i = 0; i++; i < 1000) {
        body[`${i}k`] = { [i]: 'v'.repeat(i) };
      }
      return body;
    })())
  }
];
