import { config } from './config.mjs';

/**
 * Post a comment to a GitHub PR
 */
export async function postComment(message) {
  const url = `https://api.github.com/repos/${config.REPOSITORY_OWNER}/${config.REPOSITORY}/issues/${config.PR_ID}/comments`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${config.GITHUB_TOKEN}`,
      Accept: 'application/vnd.github.v3+json',
      'User-Agent': 'perf-bot',
    },
    body: JSON.stringify({ body: message }),
  });

  if (!response.ok) {
    const text = await response.text();
    console.error(`Failed to post comment: ${response.status} ${text}`);
  } else {
    const data = await response.json();
    console.log('Comment posted:', data.html_url);
  }
}

/**
 * Generate PR comment message from comparison results
 */
export function generatePRComment(compareList) {
  let message = '[This comment is auto-generated by the perf runner]\n\n';
  message += `## Performance Comparison for PR #${config.PR_ID}, Node.js ${config.NODE_VERSION}\n\n`;

  compareList.forEach(({ testSubfolder, output }) => {
    message += `### Test Folder: ${testSubfolder}\n\n`;
    message += output.trim() + '\n\n';
  });

  return message;
}
