name: Schedule Meeting
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  meeting:
    runs-on: ubuntu-latest
    steps:
      - name: Perf WG Meeting
        uses: 'pkgjs/meet@v0'
        with:
          issueTitle: '<%= date.toFormat("yyyy-MM-dd") %> Express Performance Working Group Meeting'
          token: ${{ secrets.GITHUB_TOKEN }}
          orgs: expressjs,pillarjs,jshttp
          agendaLabel: 'perf-wg-agenda'
          meetingLabels: 'meeting'
          # https://github.com/expressjs/perf-wg/issues/2
          # Starting on 2025-05-14 at 3:00pm UTC with a period of 4 weeks (P4W)
          schedules: '2025-05-14T15:00:00.0Z/P4W'
          createWithin: 'P1W'
          issueTemplate: 'meeting.md'
